---
title: "nbaR: R access to the Netherlands Biodiversity API"
author: "Hannes Hettling"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Background

### The Netherlands Biodiversity API
The Netherlands Biodiversity API
(NBA) facilitates access to the Natural History Collection at the
Naturalis Biodiversity Center. Next to than museum specimen records
and metadata, access to taxonomic classification and nomenclature,
geographical information, and to multimedia files is provided. By
using the powerful Elasticsearch engine, the NBA facilitates searching
for collection- and biodiversity data in near real-time. Furthermore,
by incorporating information from taxonomic databases, taxonomic name
resolution can be accomplished with the NBA. Persistent Uniform
Resource Identifiers (PURLs) ensure that each species accessible via
the NBA is represented by a citable unambiguous web reference. Access
to our data is provided via a REST interface and several clients such
as the [BioPortal](http://bioportal.naturalis.nl/), a web application
for browsing biodiversity data that is served by the NBA.  For more
information about the NBA, please see our
[detailed documentation](http://docs.biodiversitydata.nl/).

### R access
The R programming language is established as a common tool in scientific resarch.
To ease the access to the NBA for researchers, we developed this R client.

## Getting started

### Main data types and classes
The data served by the NBA consists of four main data types:

* Specimen
* Taxon
* Multimedia
* Geo

Additionally, the data type *Metadata* stores miscellaneous
information about NBA settings. Each of the data types is modelled
as an `R6` class and therefore has its own members such as fields
and methods. Documentation about a specific class can be retrieved
in the standard manner:

```r
?Specimen
```

Each class of the data model can be instanciated and has a `toJSONString` and `toList` method returning
the object's JSON representation and the object's data as a list datatype, respectively.


```r
# instanciate specimen opject
spec <- Specimen$new()

# represent data as JSON or list
spec$toJSONString()
spec$toList()
```

TODO: many other classes are there

### API Client classes
The interaction with the API is accomplished by the API client classes:

* SpecimenClient
* TaxonClient
* MultimediaClient
* GeoClient
* MetadataClient


```r
# initialize client
client <- SpecimenClient$new()
```

The client class is by default initialized to connect to the base URL http://api.biodiversitydata.nl/v2.
For testing purposes, this can be set to a different URL, see `?SpecimenClient` for details.

### Queries

#### Concept

With the SpecimentClient created above, the `query` endpoint for specimens can now be reached via the `query` function.

```r
# retrieve results of empty query.
res <- client$query()
```

The `query` function then returns an object of class `Response`, which, in turn, has a field `content`
of class `QueryResult`. From the `QueryResult`, the single result items can be accessed as follows:

```r
# get first element of results
spec <- res$content$resultSet[[1]]$item

# object should be of type Specimen
class(spec)

```

#### Passing query parameters


#### Using the QuerySpec object

```r
# specify search in QueryCondition object
qc <- QueryCondition$new(field="unitID", operator="EQUALS", value="L.4304195")

# build QuerySpec using above conditions
qs <- QuerySpec$new(conditions=list(qc))

# do the query
res <- client$query(querySpec=qs)
```


```r
# specify multiple conditions
q1 <- QueryCondition$new(field = "sex", operator="EQUALS",
                         value="female")
q2 <- QueryCondition$new(field="identifications.defaultClassification.family",
                         operator="EQUALS",
                         value="Equidae")
q3 <- QueryCondition$new(field="identifications.taxonRank",
                         operator="EQUALS", value="species")

# logical conjunction using 'or' method
q3$or<- list(QueryCondition$new(field = "identifications.taxonRank",
                                operator="EQUALS",
                                value="subspecies"))

# build QuerySpec from QueryConditions
qs <-QuerySpec$new(conditions=list(q1, q2, q3))

# call API
res <-client$query(querySpec=qs)
```


```r
# get 1000 specimen items from plant order 'Gentianales'
qc <- QueryCondition$new(field = "identifications.defaultClassification.order",
                         operator="EQUALS",
                         value="Gentianales")
qs <- QuerySpec$new(conditions=list(qc), size=1000)
res <- client$query(querySpec=qs)

# extract orders from first identification of each specimen
families <- unlist(sapply(res$content$resultSet,
                          function(x)x$item$identifications[[1]]$defaultClassification$family))
# plot frequencies
barplot(table(families), horiz=T,
        col=rainbow(length(unique(families))),
        las=2, xlab="frequency", cex.names=0.5)
```


