# Netherlands Biodiversity Api
#
# Access to the digitised Natural History collection at the Naturalis Biodiversity Center
#
# OpenAPI spec version: v2
# Contact: support@naturalis.nl
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Expert Class
#'
#' @field agentText 
#' @field fullName 
#' @field organization 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Expert <- R6::R6Class(
  'Expert',
  public = list(
    `agentText` = NULL,
    `fullName` = NULL,
    `organization` = NULL,
    initialize = function(`agentText`, `fullName`, `organization`){
      if (!missing(`agentText`)) {
        stopifnot(is.character(`agentText`), length(`agentText`) == 1)
        self[['agentText']] <- `agentText`
      }
      if (!missing(`fullName`)) {
        stopifnot(is.character(`fullName`), length(`fullName`) == 1)
        self[['fullName']] <- `fullName`
      }
      if (!missing(`organization`)) {
        stopifnot(R6::is.R6(`organization`))
        self[['organization']] <- `organization`
      }
    },

    toList = function() {
      ExpertList <- list()
        if (!is.null(self[['agentText']])) {
        ExpertList[['agentText']] <- self[['agentText']]
      }
        if (!is.null(self[['fullName']])) {
        ExpertList[['fullName']] <- self[['fullName']]
      }
        if (!is.null(self[['organization']])) {
        ExpertList[['organization']] <- self[['organization']]$toList()
      }
      ## omit empty nested lists in returned list
      ExpertList[sapply(ExpertList, length) > 0]
      },

    fromList = function(ExpertList) {
      if (!is.null(ExpertList[['agentText']])) {      
          self[['agentText']] <- ExpertList[['agentText']]
      }
      if (!is.null(ExpertList[['fullName']])) {      
          self[['fullName']] <- ExpertList[['fullName']]
      }
      if (!is.null(ExpertList[['organization']])) {      
          self[['organization']] <- Organization$new()$fromList(ExpertList[['organization']])
      }
      return(self)
    },

    toJSONString = function(pretty=T) {
      jsonlite::toJSON(self$toList(), simplifyVector=T, auto_unbox=T, pretty=pretty)
    },

    fromJSONString = function(ExpertJson) {
      ExpertObject <- jsonlite::fromJSON(ExpertJson, simplifyVector=F)
      self[['agentText']] <- ExpertObject[['agentText']]
      self[['fullName']] <- ExpertObject[['fullName']]
      OrganizationObject <- Organization$new()
      self[['organization']] <- OrganizationObject$fromJSONString(jsonlite::toJSON(ExpertObject[['organization']], auto_unbox = TRUE))
      invisible(self)
    }
  )
)
