# Netherlands Biodiversity Api
#
# Access to the digitised Natural History collection at the Naturalis Biodiversity Center
#
# OpenAPI spec version: v2
# Contact: support@naturalis.nl
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Filter Class
#'
#' @field acceptRegexp 
#' @field rejectRegexp 
#' @field acceptValues 
#' @field rejectValues 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Filter <- R6::R6Class(
  'Filter',
  public = list(
    `acceptRegexp` = NULL,
    `rejectRegexp` = NULL,
    `acceptValues` = NULL,
    `rejectValues` = NULL,
    initialize = function(`acceptRegexp`, `rejectRegexp`, `acceptValues`, `rejectValues`){
      if (!missing(`acceptRegexp`)) {
        stopifnot(is.character(`acceptRegexp`), length(`acceptRegexp`) == 1)
        self[['acceptRegexp']] <- `acceptRegexp`
      }
      if (!missing(`rejectRegexp`)) {
        stopifnot(is.character(`rejectRegexp`), length(`rejectRegexp`) == 1)
        self[['rejectRegexp']] <- `rejectRegexp`
      }
      if (!missing(`acceptValues`)) {
        stopifnot(is.list(`acceptValues`), length(`acceptValues`) != 0)
        lapply(`acceptValues`, function(x) stopifnot(is.character(x)))
        self[['acceptValues']] <- `acceptValues`
      }
      if (!missing(`rejectValues`)) {
        stopifnot(is.list(`rejectValues`), length(`rejectValues`) != 0)
        lapply(`rejectValues`, function(x) stopifnot(is.character(x)))
        self[['rejectValues']] <- `rejectValues`
      }
    },

    toList = function() {
      FilterList <- list()
        if (!is.null(self[['acceptRegexp']])) {
        FilterList[['acceptRegexp']] <- self[['acceptRegexp']]
      }
        if (!is.null(self[['rejectRegexp']])) {
        FilterList[['rejectRegexp']] <- self[['rejectRegexp']]
      }
        if (!is.null(self[['acceptValues']])) {
        FilterList[['acceptValues']] <- self[['acceptValues']]
      }
        if (!is.null(self[['rejectValues']])) {
        FilterList[['rejectValues']] <- self[['rejectValues']]
      }
      ## omit empty nested lists in returned list
      FilterList[sapply(FilterList, length) > 0]
      },

    fromList = function(FilterList, typeMapping=NULL) {
      if (!is.null(FilterList[['acceptRegexp']])) {      
          self[['acceptRegexp']] <- FilterList[['acceptRegexp']]
      }
      if (!is.null(FilterList[['rejectRegexp']])) {      
          self[['rejectRegexp']] <- FilterList[['rejectRegexp']]
      }
      if (!is.null(FilterList[['acceptValues']])) {      
          self[['acceptValues']] <- FilterList[['acceptValues']]
      }
      if (!is.null(FilterList[['rejectValues']])) {      
          self[['rejectValues']] <- FilterList[['rejectValues']]
      }
      return(self)
    },

    toJSONString = function(pretty=T) {
      jsonlite::toJSON(self$toList(), simplifyVector=T, auto_unbox=T, pretty=pretty)
    },

    fromJSONString = function(FilterJson, typeMapping=NULL) {
      FilterList <- jsonlite::fromJSON(FilterJson, simplifyVector=F)
      self[['acceptRegexp']] <- FilterList[['acceptRegexp']]
      self[['rejectRegexp']] <- FilterList[['rejectRegexp']]
      self[['acceptValues']] <- FilterList[['acceptValues']]
      self[['rejectValues']] <- FilterList[['rejectValues']]
      invisible(self)
    }
  )
)
