# Netherlands Biodiversity Api
#
# Access to the digitised Natural History collection at the Naturalis Biodiversity Center
#
# OpenAPI spec version: v2
# Contact: support@naturalis.nl
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' LngLatAlt Class
#'
#' @field longitude 
#' @field latitude 
#' @field altitude 
#' @field additionalElements 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
LngLatAlt <- R6::R6Class(
  'LngLatAlt',
  public = list(
    `longitude` = NULL,
    `latitude` = NULL,
    `altitude` = NULL,
    `additionalElements` = NULL,
    initialize = function(`longitude`, `latitude`, `altitude`, `additionalElements`){
      if (!missing(`longitude`)) {
        stopifnot(is.numeric(`longitude`), length(`longitude`) == 1)
        self[['longitude']] <- `longitude`
      }
      if (!missing(`latitude`)) {
        stopifnot(is.numeric(`latitude`), length(`latitude`) == 1)
        self[['latitude']] <- `latitude`
      }
      if (!missing(`altitude`)) {
        stopifnot(is.numeric(`altitude`), length(`altitude`) == 1)
        self[['altitude']] <- `altitude`
      }
      if (!missing(`additionalElements`)) {
        stopifnot(is.list(`additionalElements`), length(`additionalElements`) != 0)
        lapply(`additionalElements`, function(x) stopifnot(is.character(x)))
        self[['additionalElements']] <- `additionalElements`
      }
    },

    toList = function() {
      LngLatAltList <- list()
        if (!is.null(self[['longitude']])) {
        LngLatAltList[['longitude']] <- self[['longitude']]
      }
        if (!is.null(self[['latitude']])) {
        LngLatAltList[['latitude']] <- self[['latitude']]
      }
        if (!is.null(self[['altitude']])) {
        LngLatAltList[['altitude']] <- self[['altitude']]
      }
        if (!is.null(self[['additionalElements']])) {
        LngLatAltList[['additionalElements']] <- self[['additionalElements']]
      }
      ## omit empty nested lists in returned list
      LngLatAltList[sapply(LngLatAltList, length) > 0]
      },

    fromList = function(LngLatAltList) {
      if (!is.null(LngLatAltList[['longitude']])) {      
          self[['longitude']] <- LngLatAltList[['longitude']]
      }
      if (!is.null(LngLatAltList[['latitude']])) {      
          self[['latitude']] <- LngLatAltList[['latitude']]
      }
      if (!is.null(LngLatAltList[['altitude']])) {      
          self[['altitude']] <- LngLatAltList[['altitude']]
      }
      if (!is.null(LngLatAltList[['additionalElements']])) {      
          self[['additionalElements']] <- LngLatAltList[['additionalElements']]
      }
      return(self)
    },

    toJSONString = function(pretty=T) {
      jsonlite::toJSON(self$toList(), simplifyVector=T, auto_unbox=T, pretty=pretty)
    },

    fromJSONString = function(LngLatAltJson) {
      LngLatAltObject <- jsonlite::fromJSON(LngLatAltJson, simplifyVector=F)
      self[['longitude']] <- LngLatAltObject[['longitude']]
      self[['latitude']] <- LngLatAltObject[['latitude']]
      self[['altitude']] <- LngLatAltObject[['altitude']]
      self[['additionalElements']] <- LngLatAltObject[['additionalElements']]
      invisible(self)
    }
  )
)
