# Netherlands Biodiversity Api
#
# Access to the digitised Natural History collection at the Naturalis Biodiversity Center
#
# OpenAPI spec version: v2
# Contact: support@naturalis.nl
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Monomial Class
#'
#' @field rank 
#' @field name 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Monomial <- R6::R6Class(
  'Monomial',
  public = list(
    `rank` = NULL,
    `name` = NULL,
    initialize = function(`rank`, `name`){
      if (!missing(`rank`)) {
        stopifnot(is.character(`rank`), length(`rank`) == 1)
        self[['rank']] <- `rank`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self[['name']] <- `name`
      }
    },

    toList = function() {
      MonomialList <- list()
        if (!is.null(self[['rank']])) {
        MonomialList[['rank']] <- self[['rank']]
      }
        if (!is.null(self[['name']])) {
        MonomialList[['name']] <- self[['name']]
      }
      ## omit empty nested lists in returned list
      MonomialList[sapply(MonomialList, length) > 0]
      },

    fromList = function(MonomialList, typeMapping=NULL) {
      if (!is.null(MonomialList[['rank']])) {      
          self[['rank']] <- MonomialList[['rank']]
      }
      if (!is.null(MonomialList[['name']])) {      
          self[['name']] <- MonomialList[['name']]
      }
      return(self)
    },

    toJSONString = function(pretty=T) {
      jsonlite::toJSON(self$toList(), simplifyVector=T, auto_unbox=T, pretty=pretty)
    },

    fromJSONString = function(MonomialJson, typeMapping=NULL) {
      MonomialList <- jsonlite::fromJSON(MonomialJson, simplifyVector=F)
      self[['rank']] <- MonomialList[['rank']]
      self[['name']] <- MonomialList[['name']]
      invisible(self)
    }
  )
)
