# Netherlands Biodiversity Api
#
# Access to the digitised Natural History collection at the Naturalis Biodiversity Center
#
# OpenAPI spec version: v2
# Contact: support@naturalis.nl
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' SpecimenIdentification Class
#'
#' @field taxonRank 
#' @field scientificName 
#' @field typeStatus 
#' @field dateIdentified 
#' @field defaultClassification 
#' @field systemClassification 
#' @field vernacularNames 
#' @field identificationQualifiers 
#' @field identifiers 
#' @field taxonomicEnrichments 
#' @field preferred 
#' @field verificationStatus 
#' @field rockType 
#' @field associatedFossilAssemblage 
#' @field rockMineralUsage 
#' @field associatedMineralName 
#' @field remarks 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SpecimenIdentification <- R6::R6Class(
  'SpecimenIdentification',
  public = list(
    `taxonRank` = NULL,
    `scientificName` = NULL,
    `typeStatus` = NULL,
    `dateIdentified` = NULL,
    `defaultClassification` = NULL,
    `systemClassification` = NULL,
    `vernacularNames` = NULL,
    `identificationQualifiers` = NULL,
    `identifiers` = NULL,
    `taxonomicEnrichments` = NULL,
    `preferred` = NULL,
    `verificationStatus` = NULL,
    `rockType` = NULL,
    `associatedFossilAssemblage` = NULL,
    `rockMineralUsage` = NULL,
    `associatedMineralName` = NULL,
    `remarks` = NULL,
    initialize = function(`taxonRank`, `scientificName`, `typeStatus`, `dateIdentified`, `defaultClassification`, `systemClassification`, `vernacularNames`, `identificationQualifiers`, `identifiers`, `taxonomicEnrichments`, `preferred`, `verificationStatus`, `rockType`, `associatedFossilAssemblage`, `rockMineralUsage`, `associatedMineralName`, `remarks`){
      if (!missing(`taxonRank`)) {
        stopifnot(is.character(`taxonRank`), length(`taxonRank`) == 1)
        self[['taxonRank']] <- `taxonRank`
      }
      if (!missing(`scientificName`)) {
        stopifnot(R6::is.R6(`scientificName`))
        self[['scientificName']] <- `scientificName`
      }
      if (!missing(`typeStatus`)) {
        stopifnot(is.character(`typeStatus`), length(`typeStatus`) == 1)
        self[['typeStatus']] <- `typeStatus`
      }
      if (!missing(`dateIdentified`)) {
        stopifnot(is.character(`dateIdentified`), length(`dateIdentified`) == 1)
        self[['dateIdentified']] <- `dateIdentified`
      }
      if (!missing(`defaultClassification`)) {
        stopifnot(R6::is.R6(`defaultClassification`))
        self[['defaultClassification']] <- `defaultClassification`
      }
      if (!missing(`systemClassification`)) {
        stopifnot(is.list(`systemClassification`), length(`systemClassification`) != 0)
        lapply(`systemClassification`, function(x) stopifnot(R6::is.R6(x)))
        self[['systemClassification']] <- `systemClassification`
      }
      if (!missing(`vernacularNames`)) {
        stopifnot(is.list(`vernacularNames`), length(`vernacularNames`) != 0)
        lapply(`vernacularNames`, function(x) stopifnot(R6::is.R6(x)))
        self[['vernacularNames']] <- `vernacularNames`
      }
      if (!missing(`identificationQualifiers`)) {
        stopifnot(is.list(`identificationQualifiers`), length(`identificationQualifiers`) != 0)
        lapply(`identificationQualifiers`, function(x) stopifnot(is.character(x)))
        self[['identificationQualifiers']] <- `identificationQualifiers`
      }
      if (!missing(`identifiers`)) {
        stopifnot(is.list(`identifiers`), length(`identifiers`) != 0)
        lapply(`identifiers`, function(x) stopifnot(R6::is.R6(x)))
        self[['identifiers']] <- `identifiers`
      }
      if (!missing(`taxonomicEnrichments`)) {
        stopifnot(is.list(`taxonomicEnrichments`), length(`taxonomicEnrichments`) != 0)
        lapply(`taxonomicEnrichments`, function(x) stopifnot(R6::is.R6(x)))
        self[['taxonomicEnrichments']] <- `taxonomicEnrichments`
      }
      if (!missing(`preferred`)) {
        self[['preferred']] <- `preferred`
      }
      if (!missing(`verificationStatus`)) {
        stopifnot(is.character(`verificationStatus`), length(`verificationStatus`) == 1)
        self[['verificationStatus']] <- `verificationStatus`
      }
      if (!missing(`rockType`)) {
        stopifnot(is.character(`rockType`), length(`rockType`) == 1)
        self[['rockType']] <- `rockType`
      }
      if (!missing(`associatedFossilAssemblage`)) {
        stopifnot(is.character(`associatedFossilAssemblage`), length(`associatedFossilAssemblage`) == 1)
        self[['associatedFossilAssemblage']] <- `associatedFossilAssemblage`
      }
      if (!missing(`rockMineralUsage`)) {
        stopifnot(is.character(`rockMineralUsage`), length(`rockMineralUsage`) == 1)
        self[['rockMineralUsage']] <- `rockMineralUsage`
      }
      if (!missing(`associatedMineralName`)) {
        stopifnot(is.character(`associatedMineralName`), length(`associatedMineralName`) == 1)
        self[['associatedMineralName']] <- `associatedMineralName`
      }
      if (!missing(`remarks`)) {
        stopifnot(is.character(`remarks`), length(`remarks`) == 1)
        self[['remarks']] <- `remarks`
      }
    },

    toList = function() {
      SpecimenIdentificationList <- list()
        if (!is.null(self[['taxonRank']])) {
        SpecimenIdentificationList[['taxonRank']] <- self[['taxonRank']]
      }
        if (!is.null(self[['scientificName']])) {
        SpecimenIdentificationList[['scientificName']] <- self[['scientificName']]$toList()
      }
        if (!is.null(self[['typeStatus']])) {
        SpecimenIdentificationList[['typeStatus']] <- self[['typeStatus']]
      }
        if (!is.null(self[['dateIdentified']])) {
        SpecimenIdentificationList[['dateIdentified']] <- self[['dateIdentified']]
      }
        if (!is.null(self[['defaultClassification']])) {
        SpecimenIdentificationList[['defaultClassification']] <- self[['defaultClassification']]$toList()
      }
        if (!is.null(self[['systemClassification']])) {
        SpecimenIdentificationList[['systemClassification']] <- lapply(self[['systemClassification']], function(x) x$toList())
      }
        if (!is.null(self[['vernacularNames']])) {
        SpecimenIdentificationList[['vernacularNames']] <- lapply(self[['vernacularNames']], function(x) x$toList())
      }
        if (!is.null(self[['identificationQualifiers']])) {
        SpecimenIdentificationList[['identificationQualifiers']] <- self[['identificationQualifiers']]
      }
        if (!is.null(self[['identifiers']])) {
        SpecimenIdentificationList[['identifiers']] <- lapply(self[['identifiers']], function(x) x$toList())
      }
        if (!is.null(self[['taxonomicEnrichments']])) {
        SpecimenIdentificationList[['taxonomicEnrichments']] <- lapply(self[['taxonomicEnrichments']], function(x) x$toList())
      }
        if (!is.null(self[['preferred']])) {
        SpecimenIdentificationList[['preferred']] <- self[['preferred']]
      }
        if (!is.null(self[['verificationStatus']])) {
        SpecimenIdentificationList[['verificationStatus']] <- self[['verificationStatus']]
      }
        if (!is.null(self[['rockType']])) {
        SpecimenIdentificationList[['rockType']] <- self[['rockType']]
      }
        if (!is.null(self[['associatedFossilAssemblage']])) {
        SpecimenIdentificationList[['associatedFossilAssemblage']] <- self[['associatedFossilAssemblage']]
      }
        if (!is.null(self[['rockMineralUsage']])) {
        SpecimenIdentificationList[['rockMineralUsage']] <- self[['rockMineralUsage']]
      }
        if (!is.null(self[['associatedMineralName']])) {
        SpecimenIdentificationList[['associatedMineralName']] <- self[['associatedMineralName']]
      }
        if (!is.null(self[['remarks']])) {
        SpecimenIdentificationList[['remarks']] <- self[['remarks']]
      }
      ## omit empty nested lists in returned list
      SpecimenIdentificationList[sapply(SpecimenIdentificationList, length) > 0]
      },

    fromList = function(SpecimenIdentificationList, typeObject=NULL) {
      if (!is.null(SpecimenIdentificationList[['taxonRank']])) {      
          self[['taxonRank']] <- SpecimenIdentificationList[['taxonRank']]
      }
      if (!is.null(SpecimenIdentificationList[['scientificName']])) {      
          if (is.null(typeObject)) {
              self[['scientificName']] <- ScientificName$new()$fromList(SpecimenIdentificationList[['scientificName']])
          } else {
              self[['scientificName']] <- typeObject$fromList(SpecimenIdentificationList[['scientificName']])
          }
      }
      if (!is.null(SpecimenIdentificationList[['typeStatus']])) {      
          self[['typeStatus']] <- SpecimenIdentificationList[['typeStatus']]
      }
      if (!is.null(SpecimenIdentificationList[['dateIdentified']])) {      
          self[['dateIdentified']] <- SpecimenIdentificationList[['dateIdentified']]
      }
      if (!is.null(SpecimenIdentificationList[['defaultClassification']])) {      
          if (is.null(typeObject)) {
              self[['defaultClassification']] <- DefaultClassification$new()$fromList(SpecimenIdentificationList[['defaultClassification']])
          } else {
              self[['defaultClassification']] <- typeObject$fromList(SpecimenIdentificationList[['defaultClassification']])
          }
      }
      if (!is.null(SpecimenIdentificationList[['systemClassification']])) {      
          self[['systemClassification']] <- lapply(SpecimenIdentificationList[['systemClassification']], function(x) {
             Monomial$new()$fromList(x, typeObject=typeObject)            
          })
      }
      if (!is.null(SpecimenIdentificationList[['vernacularNames']])) {      
          self[['vernacularNames']] <- lapply(SpecimenIdentificationList[['vernacularNames']], function(x) {
             VernacularName$new()$fromList(x, typeObject=typeObject)            
          })
      }
      if (!is.null(SpecimenIdentificationList[['identificationQualifiers']])) {      
          self[['identificationQualifiers']] <- SpecimenIdentificationList[['identificationQualifiers']]
      }
      if (!is.null(SpecimenIdentificationList[['identifiers']])) {      
          self[['identifiers']] <- lapply(SpecimenIdentificationList[['identifiers']], function(x) {
             Agent$new()$fromList(x, typeObject=typeObject)            
          })
      }
      if (!is.null(SpecimenIdentificationList[['taxonomicEnrichments']])) {      
          self[['taxonomicEnrichments']] <- lapply(SpecimenIdentificationList[['taxonomicEnrichments']], function(x) {
             TaxonomicEnrichment$new()$fromList(x, typeObject=typeObject)            
          })
      }
      if (!is.null(SpecimenIdentificationList[['preferred']])) {      
          self[['preferred']] <- SpecimenIdentificationList[['preferred']]
      }
      if (!is.null(SpecimenIdentificationList[['verificationStatus']])) {      
          self[['verificationStatus']] <- SpecimenIdentificationList[['verificationStatus']]
      }
      if (!is.null(SpecimenIdentificationList[['rockType']])) {      
          self[['rockType']] <- SpecimenIdentificationList[['rockType']]
      }
      if (!is.null(SpecimenIdentificationList[['associatedFossilAssemblage']])) {      
          self[['associatedFossilAssemblage']] <- SpecimenIdentificationList[['associatedFossilAssemblage']]
      }
      if (!is.null(SpecimenIdentificationList[['rockMineralUsage']])) {      
          self[['rockMineralUsage']] <- SpecimenIdentificationList[['rockMineralUsage']]
      }
      if (!is.null(SpecimenIdentificationList[['associatedMineralName']])) {      
          self[['associatedMineralName']] <- SpecimenIdentificationList[['associatedMineralName']]
      }
      if (!is.null(SpecimenIdentificationList[['remarks']])) {      
          self[['remarks']] <- SpecimenIdentificationList[['remarks']]
      }
      return(self)
    },

    toJSONString = function(pretty=T) {
      jsonlite::toJSON(self$toList(), simplifyVector=T, auto_unbox=T, pretty=pretty)
    },

    fromJSONString = function(SpecimenIdentificationJson, typeObject=NULL) {
      SpecimenIdentificationList <- jsonlite::fromJSON(SpecimenIdentificationJson, simplifyVector=F)
      self[['taxonRank']] <- SpecimenIdentificationList[['taxonRank']]
      if (is.null(typeObject)) {
          self[['scientificName']] <- ScientificName$new()$fromJSONString(jsonlite::toJSON(SpecimenIdentificationList[['scientificName']], auto_unbox = TRUE), typeObject=typeObject) 
      } else {
          self[['scientificName']] <- typeObject$fromJSONString(jsonlite::toJSON(SpecimenIdentificationList[['scientificName']], auto_unbox = TRUE), typeObject=typeObject)
      }
      self[['typeStatus']] <- SpecimenIdentificationList[['typeStatus']]
      self[['dateIdentified']] <- SpecimenIdentificationList[['dateIdentified']]
      if (is.null(typeObject)) {
          self[['defaultClassification']] <- DefaultClassification$new()$fromJSONString(jsonlite::toJSON(SpecimenIdentificationList[['defaultClassification']], auto_unbox = TRUE), typeObject=typeObject) 
      } else {
          self[['defaultClassification']] <- typeObject$fromJSONString(jsonlite::toJSON(SpecimenIdentificationList[['defaultClassification']], auto_unbox = TRUE), typeObject=typeObject)
      }
      self[['systemClassification']] <- lapply(SpecimenIdentificationList[['systemClassification']],
                                        function(x) Monomial$new()$fromJSONString(jsonlite::toJSON(x, auto_unbox = TRUE), typeObject=typeObject))
      self[['vernacularNames']] <- lapply(SpecimenIdentificationList[['vernacularNames']],
                                        function(x) VernacularName$new()$fromJSONString(jsonlite::toJSON(x, auto_unbox = TRUE), typeObject=typeObject))
      self[['identificationQualifiers']] <- SpecimenIdentificationList[['identificationQualifiers']]
      self[['identifiers']] <- lapply(SpecimenIdentificationList[['identifiers']],
                                        function(x) Agent$new()$fromJSONString(jsonlite::toJSON(x, auto_unbox = TRUE), typeObject=typeObject))
      self[['taxonomicEnrichments']] <- lapply(SpecimenIdentificationList[['taxonomicEnrichments']],
                                        function(x) TaxonomicEnrichment$new()$fromJSONString(jsonlite::toJSON(x, auto_unbox = TRUE), typeObject=typeObject))
      self[['preferred']] <- SpecimenIdentificationList[['preferred']]
      self[['verificationStatus']] <- SpecimenIdentificationList[['verificationStatus']]
      self[['rockType']] <- SpecimenIdentificationList[['rockType']]
      self[['associatedFossilAssemblage']] <- SpecimenIdentificationList[['associatedFossilAssemblage']]
      self[['rockMineralUsage']] <- SpecimenIdentificationList[['rockMineralUsage']]
      self[['associatedMineralName']] <- SpecimenIdentificationList[['associatedMineralName']]
      self[['remarks']] <- SpecimenIdentificationList[['remarks']]
      invisible(self)
    }
  )
)
