# Netherlands Biodiversity Api
#
# Access to the digitised Natural History collection at the Naturalis Biodiversity Center
#
# OpenAPI spec version: v2
# Contact: support@naturalis.nl
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' SummarySourceSystem Class
#'
#' @field code 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SummarySourceSystem <- R6::R6Class(
  'SummarySourceSystem',
  public = list(
    `code` = NULL,
    initialize = function(`code`){
      if (!missing(`code`)) {
        stopifnot(is.character(`code`), length(`code`) == 1)
        self[['code']] <- `code`
      }
    },

    toList = function() {
      SummarySourceSystemList <- list()
        if (!is.null(self[['code']])) {
        SummarySourceSystemList[['code']] <- self[['code']]
      }
      ## omit empty nested lists in returned list
      SummarySourceSystemList[sapply(SummarySourceSystemList, length) > 0]
      },

    fromList = function(SummarySourceSystemList) {
      if (!is.null(SummarySourceSystemList[['code']])) {      
          self[['code']] <- SummarySourceSystemList[['code']]
      }
      return(self)
    },

    toJSONString = function(pretty=T) {
      jsonlite::toJSON(self$toList(), simplifyVector=T, auto_unbox=T, pretty=pretty)
    },

    fromJSONString = function(SummarySourceSystemJson) {
      SummarySourceSystemObject <- jsonlite::fromJSON(SummarySourceSystemJson, simplifyVector=F)
      self[['code']] <- SummarySourceSystemObject[['code']]
      invisible(self)
    }
  )
)
