# Netherlands Biodiversity API
#
# Access to the digitised Natural History collection at the Naturalis Biodiversity Center
#
# OpenAPI spec version: v2
# Contact: support@naturalis.nl
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' TaxonomicEnrichment Class
#'
#'
#'
#' @field vernacularNames  list(SummaryVernacularName)
#' @field synonyms  list(SummaryScientificName)
#' @field sourceSystem  SummarySourceSystem
#' @field taxonId  character
#'
#' @section Methods:
#' \describe{
#'
#' \item{\code{$new()}}{
#'
#'   Constructor TaxonomicEnrichment object.
#'
#' }
#' \item{\code{$fromList(TaxonomicEnrichmentList)}}{
#'
#'   Create TaxonomicEnrichment object from list.
#'
#' }
#'
#' \item{\code{$toList()}}{
#'
#'   Get list representation of TaxonomicEnrichment.
#'
#' }
#' \item{\code{fromJSONString(TaxonomicEnrichmentJson)}}{
#'
#'   Create TaxonomicEnrichment object from list.
#'
#' }
#' \item{\code{toJSONString(pretty=TRUE)}}{
#'
#'   Get JSON representation of TaxonomicEnrichment.
#'
#' }
#' }
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TaxonomicEnrichment <- R6::R6Class(
  "TaxonomicEnrichment",
  public = list(
    `vernacularNames` = NULL,
    `synonyms` = NULL,
    `sourceSystem` = NULL,
    `taxonId` = NULL,
    initialize = function(
                              `vernacularNames`,
                              `synonyms`,
                              `sourceSystem`,
                              `taxonId`) {
      if (!missing(`vernacularNames`)) {
        stopifnot(
          is.list(`vernacularNames`),
          length(`vernacularNames`) != 0
        )
        lapply(
          `vernacularNames`,
          function(x) stopifnot(R6::is.R6(x))
        )
        self[["vernacularNames"]] <- `vernacularNames`
      }
      if (!missing(`synonyms`)) {
        stopifnot(
          is.list(`synonyms`),
          length(`synonyms`) != 0
        )
        lapply(
          `synonyms`,
          function(x) stopifnot(R6::is.R6(x))
        )
        self[["synonyms"]] <- `synonyms`
      }
      if (!missing(`sourceSystem`)) {
        stopifnot(R6::is.R6(`sourceSystem`))
        self[["sourceSystem"]] <- `sourceSystem`
      }
      if (!missing(`taxonId`)) {
        stopifnot(
          is.character(`taxonId`),
          length(`taxonId`) == 1
        )
        self[["taxonId"]] <- `taxonId`
      }
    },
    toList = function() {
      TaxonomicEnrichmentList <- list()
      if (!is.null(self[["vernacularNames"]])) {
        TaxonomicEnrichmentList[["vernacularNames"]] <-
          lapply(self[["vernacularNames"]], function(x) x$toList())
      }
      if (!is.null(self[["synonyms"]])) {
        TaxonomicEnrichmentList[["synonyms"]] <-
          lapply(self[["synonyms"]], function(x) x$toList())
      }
      if (!is.null(self[["sourceSystem"]])) {
        TaxonomicEnrichmentList[["sourceSystem"]] <-
          self[["sourceSystem"]]$toList()
      }
      if (!is.null(self[["taxonId"]])) {
        TaxonomicEnrichmentList[["taxonId"]] <-
          self[["taxonId"]]
      }
      ## omit empty nested lists in returned list
      TaxonomicEnrichmentList[vapply(
        TaxonomicEnrichmentList,
        length,
        FUN.VALUE = integer(1)
      ) > 0]
    },
    fromList = function(TaxonomicEnrichmentList,
                            typeMapping = NULL) {
      self[["vernacularNames"]] <- lapply(
        TaxonomicEnrichmentList[["vernacularNames"]],
        function(x) {
          SummaryVernacularName$new()$fromList(x,
            typeMapping = typeMapping
          )
        }
      )
      self[["synonyms"]] <- lapply(
        TaxonomicEnrichmentList[["synonyms"]],
        function(x) {
          SummaryScientificName$new()$fromList(x,
            typeMapping = typeMapping
          )
        }
      )
      self[["sourceSystem"]] <- SummarySourceSystem$new()$fromList(
        TaxonomicEnrichmentList[["sourceSystem"]],
        typeMapping = typeMapping
      )
      self[["taxonId"]] <-
        TaxonomicEnrichmentList[["taxonId"]]
      invisible(self)
    },
    toJSONString = function(pretty = TRUE) {
      jsonlite::toJSON(
        self$toList(),
        simplifyVector = TRUE,
        auto_unbox = TRUE,
        pretty = pretty
      )
    },
    fromJSONString = function(TaxonomicEnrichmentJson,
                                  typeMapping = NULL) {
      TaxonomicEnrichmentList <- jsonlite::fromJSON(
        TaxonomicEnrichmentJson,
        simplifyVector = FALSE
      )
      self <- self$fromList(TaxonomicEnrichmentList)
      invisible(self)
    }
  )
)
