# Netherlands Biodiversity Api
# 
# Access to the digitised Natural History collection at the Naturalis Biodiversity Center
# 
# OpenAPI spec version: v2
# Contact: support@naturalis.nl
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' TaxonomicEnrichment Class
#'
#' @field vernacularNames 
#' @field synonyms 
#' @field sourceSystem 
#' @field taxonId 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TaxonomicEnrichment <- R6::R6Class(
  'TaxonomicEnrichment',
  public = list(
    `vernacularNames` = NULL,
    `synonyms` = NULL,
    `sourceSystem` = NULL,
    `taxonId` = NULL,
    initialize = function(`vernacularNames`, `synonyms`, `sourceSystem`, `taxonId`){
      if (!missing(`vernacularNames`)) {
        stopifnot(is.list(`vernacularNames`), length(`vernacularNames`) != 0)
        lapply(`vernacularNames`, function(x) stopifnot(R6::is.R6(x)))
        self$`vernacularNames` <- `vernacularNames`
      }
      if (!missing(`synonyms`)) {
        stopifnot(is.list(`synonyms`), length(`synonyms`) != 0)
        lapply(`synonyms`, function(x) stopifnot(R6::is.R6(x)))
        self$`synonyms` <- `synonyms`
      }
      if (!missing(`sourceSystem`)) {
        stopifnot(R6::is.R6(`sourceSystem`))
        self$`sourceSystem` <- `sourceSystem`
      }
      if (!missing(`taxonId`)) {
        stopifnot(is.character(`taxonId`), length(`taxonId`) == 1)
        self$`taxonId` <- `taxonId`
      }
    },
    toJSON = function() {
      TaxonomicEnrichmentObject <- list()
      if (!is.null(self$`vernacularNames`)) {
        TaxonomicEnrichmentObject[['vernacularNames']] <- lapply(self$`vernacularNames`, function(x) x$toJSON())
      }
      if (!is.null(self$`synonyms`)) {
        TaxonomicEnrichmentObject[['synonyms']] <- lapply(self$`synonyms`, function(x) x$toJSON())
      }
      if (!is.null(self$`sourceSystem`)) {
        TaxonomicEnrichmentObject[['sourceSystem']] <- self$`sourceSystem`$toJSON()
      }
      if (!is.null(self$`taxonId`)) {
        TaxonomicEnrichmentObject[['taxonId']] <- self$`taxonId`
      }

      TaxonomicEnrichmentObject
    },
    fromJSON = function(TaxonomicEnrichmentJson) {
      TaxonomicEnrichmentObject <- jsonlite::fromJSON(TaxonomicEnrichmentJson, simplifyVector=F)
      if (!is.null(TaxonomicEnrichmentObject$`vernacularNames`)) {
        self$`vernacularNames` <- lapply(TaxonomicEnrichmentObject$`vernacularNames`, function(x) {
          vernacularNamesObject <- SummaryVernacularName$new()
          vernacularNamesObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          vernacularNamesObject
        })
      }
      if (!is.null(TaxonomicEnrichmentObject$`synonyms`)) {
        self$`synonyms` <- lapply(TaxonomicEnrichmentObject$`synonyms`, function(x) {
          synonymsObject <- SummaryScientificName$new()
          synonymsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          synonymsObject
        })
      }
      if (!is.null(TaxonomicEnrichmentObject$`sourceSystem`)) {
        sourceSystemObject <- SummarySourceSystem$new()
        sourceSystemObject$fromJSON(jsonlite::toJSON(TaxonomicEnrichmentObject$sourceSystem, auto_unbox = TRUE))
        self$`sourceSystem` <- sourceSystemObject
      }
      if (!is.null(TaxonomicEnrichmentObject$`taxonId`)) {
        self$`taxonId` <- TaxonomicEnrichmentObject$`taxonId`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "vernacularNames": [%s],
           "synonyms": [%s],
           "sourceSystem": %s,
           "taxonId": %s
        }',
        lapply(self$`vernacularNames`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`synonyms`, function(x) paste(x$toJSON(), sep=",")),
        self$`sourceSystem`$toJSON(),
        self$`taxonId`
      )
    },
    fromJSONString = function(TaxonomicEnrichmentJson) {
      TaxonomicEnrichmentObject <- jsonlite::fromJSON(TaxonomicEnrichmentJson)
      self$`vernacularNames` <- lapply(TaxonomicEnrichmentObject$`vernacularNames`, function(x) SummaryVernacularName$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`synonyms` <- lapply(TaxonomicEnrichmentObject$`synonyms`, function(x) SummaryScientificName$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      SummarySourceSystemObject -> SummarySourceSystem$new()
      self$`sourceSystem` <- SummarySourceSystemObject$fromJSON(jsonlite::toJSON(TaxonomicEnrichmentObject$sourceSystem, auto_unbox = TRUE))
      self$`taxonId` <- TaxonomicEnrichmentObject$`taxonId`
    }
  )
)
